version: 0.2

phases:
  pre_build:
    commands:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg     
      - docker login -u "moindev" -p "Thequint@101992" docker.io
      - apt-get update
      - apt-get install -y build-essential
      - apt-get install -y imagemagick libmagickwand-dev
      - gem install bundler
      - apt-get install -y nodejs

  install:
    runtime-versions:
      ruby: 3.1.2

  build:
    commands:
      - bundle install --verbose
      - convert -version  # Check ImageMagick version
      - echo Building RoR application...
      # Add your build commands here

  post_build:
    commands:
      - echo Post build steps...
      - bundle exec rails db:create
      - bundle exec rails db:migrate
      - bundle exec rails s

      # Add any post-build steps here
