version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo Installing dependencies...
     

  pre_build:
    commands:
      - gem install bundler

  build:
    commands:
     - bundle install --path=.bundle
     - echo Building RoR application...
      # Add your build commands here

  post_build:
    commands:
      - echo Post build steps...
      # Add any post-build steps here
