version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1.2
    commands:
      - echo Installing dependencies...
      - bundle install --path=.bundle

  pre_build:
    commands:
      - echo Preparing for build...

  build:
    commands:
      - echo Building RoR application...
      # Add your build commands here

  post_build:
    commands:
      - echo Post build steps...
      # Add any post-build steps here
