version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends imagemagick
      - gem install bundler

  install:
    runtime-versions:
      ruby: 3.1.2

  build:
    commands:
      - bundle install --verbose
      - echo Building RoR application...
      # Add your build commands here

  post_build:
    commands:
      - echo Post build steps...
      # Add any post-build steps here
