version: 0.2

phases:
  pre_build:
    commands:      
      - docker login -u "moindev" -p "Thequint@101992" docker.io
     
      


  install:
    runtime-versions:
      ruby: 3.1.2

  build:
    commands:
      - docker build --no-cache  -t feetet/ecom:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push moindev/moin-blog-frontend:$CI_COMMIT_SHORT_SHA
      # Add your build commands here

  post_build:
    commands:
      - echo Post build steps...
  

      # Add any post-build steps here
