version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - echo Installing dependencies...
     

  pre_build:
    commands: 
      - yum install -y ImageMagick
      - gem install bundler


  build:
    commands:
     - bundle install --verbose
     - echo Building RoR application...
      # Add your build commands here

  post_build:
    commands:
      - echo Post build steps...
      # Add any post-build steps here
